# Use the official image as a parent image.
FROM alpine:latest

# Set the working directory.
WORKDIR /usr/src

# Copy the file from your host to your current location.
COPY /publisher/sv_publisher .
COPY /subscriber/

# Run the command inside your image filesystem.
RUN python3

# Inform Docker that the container is listening on the specified port at runtime.

# Run the specified command within the container.
CMD [ "npm", "start" ]

# Copy the rest of your app's source code from your host to your image filesystem.
COPY . .

